MaaAssistantArknights/maa-cli

- maa-run/src/message.rs
The unknown message will be printed to trace log, and the failed message will be printed to debug log. Because the unknown message is too many, and the failed message is more important.
> feat: failed message will be printed to debug log

- maa-run/src/main.rs
This is useful for users who want to change some configuration of MaaCore, but don't want to modify the source code. Now, they can just copy the resource file to a new location (for example, `~/.config/maa/resource`), and specify the absolute path in the `asst.toml` file.
> feat: support absolute path for additional resource

- Cargo.lock
- maa-cli/Cargo.toml
- maa-cli/src/run/mod.rs
之前收到终止信号的时候不会 drop 局部变量, 这样如果不调用 `AsstDestroy` 而终止进程可能出一些问题比如 coredump, 甚至生成奇奇怪怪的文件 (MaaAssistantArknights/MaaAssistantArknights#5255).
所以加了个处理信号的东西
`signal-hook` 声称 Windows 下也能用, 这个我没测试过.
~~`tokio` 似乎也有处理 Ctrl+C 的东西不过要加一堆异步的玩意, 还是算了~~
> feat: drop assistant on Ctrl+C

- maa-cli/src/installer/maa_core.rs
If libs are installed at a public dir, this will delete all files in that dir.
> fix: don't ensure `lib_dir` clean

- maa-cli/src/config/cli.rs
- maa-cli/src/config/mod.rs
- maa-cli/src/installer/maa_core.rs
- maa-cli/src/main.rs
CLI config file in `$MAA_CONFIG_DIR/cli.toml`.
Currently, there only one field `channel` used to set update channel of MaaCore.
> feat: add CLI config file

- maa-cli/src/installer/extract.rs
In some cases, the files with same size are not same. For example, MaaCore v4.23.0 and v4.23.1 have the same size, which breaks `maa update`.
> fix: don't skip file with same size

- maa-cli/src/config/cli.rs
- maa-cli/src/main.rs
This commit adds a `core` field to the CLI configuration. This field contains the channel to update the MaaCore and the components to install.
The `channel` field is deprecated and will be removed in the future.
> feat: add `core` field to CLI configuration

- maa-cli/src/installer/maa_core.rs
If this cli is installed by a package manager, this feature is useful to find the resource directory from MaaCore installed by the package manager.
Closes #42
> feat: `MAA_EXTRA_SHARE_NAME` to specify extra share name at compile time

- maa-cli/Cargo.toml
- maa-cli/src/installer/mod.rs
- maa-cli/src/main.rs
If `maa-cli` is installed by some package manager like `brew`, self update is not needed and not encouraged.
> feat:  add a feature `self` to disable self update by disable it

- .github/workflows/arch-package.yml
- .github/workflows/publish-aur.yml
This workflow would build and push new version number to `aur.archlinux.org/maa-cli.git` when a new tag was pushed.
Sed scripts were copied from [arch_package.yml](https://github.com/hykilpikonna/hyfetch/blob/master/.github/workflows/arch_package.yml)
> Add workflow to update aur repo automatically

- .github/workflows/publish-aur.yml
- .github/workflows/publish-homebrew.yml
- .github/workflows/release.yml
Release created by ci will [not trigger other workflows run](https://docs.github.com/en/actions/using-workflows/triggering-a-workflow#triggering-a-workflow-from-a-workflow). So we need to call workflow in release workflow.
> ci: call `publish-*` workflows after release

- maa-cli/src/run/mod.rs
If the given name is a library name, `dlopen` will  do search. It will search paths, such as paths defined in `LD_LIBRARY_PATH` on linux and `DYLD_LIBRARY_PATH` on macOS.
Part of #67.
> feat: load `MaaCore` with name if core dir not found

- maa-cli/src/installer/maa_cli.rs
- maa-cli/src/installer/maa_core.rs
If the current executable is a symlink, `current_exe` returns the path of the symlink, not the path of the target in some platforms. This commit fixes it by calling `canonicalize` on the returned path.
See #67
> fix: canonicalize returned path of `current_exe`

- maa-cli/src/main.rs
- maa-cli/src/run/mod.rs
If the type of `user_resource` is `Option<bool>`, it requires the user to specify the value of `user_resource` when running the command `maa run`.
> fix: `user_resource` should be a bool instead of an option 

- maa-cli/src/run/mod.rs
The load of client resource should not be affected by the value of `playtools`.
> fix: load client resource when `playtools` is false

- .github/workflows/ci.yml
- config_examples/asst.toml
- maa-cli/src/config/asst.rs
- maa-cli/src/main.rs
- maa-cli/src/run/mod.rs
This option is useful user check their config file, and run tests in CI. May be used in unit tests in the future.
> feat: add `--dry-run` option to run command

- maa-cli/src/run/mod.rs
Try run with `MaaCore` failed to exit in CI.
See: https://github.com/MaaAssistantArknights/maa-cli/actions/runs/6516174359/job/17699423949
It seems caused by `stop_bool.store(true, std::sync::atomic::Ordering::Relaxed)`,
see https://github.com/MaaAssistantArknights/maa-cli/actions/runs/6516380388/job/17699850335?pr=79#step:9:41.
Solution: We disable signal handling on windows as a temporary fix. But we can't remove `signal_hook` from dependencies on windows now, because of lifetime of variable in conditional block.
> fix: failed to exit on windows

- .github/workflows/ci.yml
See https://community.codecov.com/t/upload-issues-unable-to-locate-build-via-github-actions-api/3954
> ci: upload coverage with token

- maa-cli/src/installer/maa_cli.rs
- maa-cli/src/installer/maa_core.rs
In recent changes, we force `current_exe` to be canonicalized. However, for homebrew, `maa` is installed in separate directory, and linked to `/usr/local/bin/maa` or `/opt/homebrew/bin/maa`. To search library and resource also installed by homebrew, we need to search the origin directory of `current_exe`. So we search both origin and canonicalized directory of `current_exe`.
> feat: search both origin and canonicalized directory of `current_exe`

- maa-cli/src/config/task/mod.rs
- maa-cli/src/run/fight.rs
- maa-cli/src/run/mod.rs
The `TaskList` struct is renamed to `TaskConfig` because it may not only contain a list of tasks. It may also contain other information in the future.
> refactor: rename `TaskList` to `TaskConfig` and add methods

- maa-cli/src/main.rs
- maa-cli/src/run/fight.rs
- maa-cli/src/run/mod.rs
There are some common args in `run` and related subcommands `fight` or coming `copilot`, so move them in a struct `CommonArgs` to avoid repeating.
> refactor: move common args of `run` in struct `CommonArgs`

- .github/scripts/parse_version.sh
- .github/workflows/release.yml
The git-cliff action always compares the current HEAD to the last tag. However, we want to compare beta releases to the last beta release and stable releases to the last stable release.
> ci: generate release notes based on the last release

- .github/workflows/release.yml
For nightly release, we should clear existing release and tag. For other release, we should check if the release already exists, and abort if it does.
> ci: check existing release before publishing

- .github/scripts/parse_version.sh
- .github/workflows/release.yml
- cliff.toml
So far, we have been using the `compare_base` output from the `parse_version.sh` script to determine the range of commits to be included in the changelog. This not works well,
because the pre-release also splits the commits into multiple groups. For example, if the last stable release is `v0.1.0`, and last beta release is `v0.1.1-beta.1`, then the changelog from head will include all commits from `v0.1.0` to head, but they will be split into two groups: `v0.1.0..v0.1.1-beta.1` and `v0.1.1-beta.1..HEAD`. This is not what we want.
So instead of using `compare_base`, we use the `tag_pattern` to filter out pre-releases. This will ensure that the changelog compares to the last stable release, and they are grouped into a single group.
> ci: use tag pattern to filter out pre-releases

- Cargo.lock
- maa-cli/Cargo.toml
- maa-cli/src/main.rs
- maa-cli/src/run/copilot.rs
- maa-cli/src/run/mod.rs
In fact, it is PR #103. But I had done something wrong that had forced the closure of PR #103 when I tried to rebase the newest commit. 
In the new version, it uses `BoolInput` to receive the user's selection. Moreover, it adds two features. One is the ability to identify JSON files, and the other is the capability to read the clipboard with the option "--paste".
In passing, should "Cargo.lock" be tracked by git? Like "package-lock.json" of node.
> feat: add SubCommand `copliot` to complete the auto-battle feature 

- .github/workflows/release.yml
- maa-cli/src/installer/maa_cli.rs
- maa-cli/src/run/playcover.rs
Currently, the build for `x86_64-apple-darwin` and `aarch64-apple-darwin` are not the same. The `aarch64` build with `vendored` openssl, while the `x86_64` build uses the system openssl.
> feat!: download native binaries instead of universal binaries on macOS

- maa-cli/src/config/asst.rs
The CI fails with message "Cannot create a file when that file already exists", which might be caused by the test trying to create the user resource directory twice. However, I have no idea why this happens on CI, because lazy_static is supposed to be initialized only once.
> test: fix test failure on CI caused by create user resource dir

- maa-sys/src/asst_type.rs
There may be some issues with MaaCore, run test in CI will cause the double free or corruption error. So we disable the test in CI.
> feat: don't run set options test in CI

- maa-cli/src/dirs.rs
> fix!: ensure extra share name is a name instead of a path

- .github/workflows/ci.yml
The most expensive part of the CI is the coverage job, so build jobs without coverage is much faster. Due to the storage limit of cache, we can't cache for all jobs, so we only cache for jobs with coverage.
> ci: don't cache for jobs without coverage

- maa-cli/src/value/mod.rs
- maa-cli/src/value/primate.rs
The return type is `Option<&str>`, so `as_str` is a more appropriate.
> chore: rename `as_string` to `as_str`

- .github/workflows/release.yml
User may not have openssl installed on their system, so we should always build with vendored-openssl.
> ci: release with`vendored-openssl` on all arches

- README-EN.md
- README.md
- maa-cli/Cargo.toml
- maa-cli/src/config/task/condition.rs
This will address issues with tests near midnight. However, if the start or end times are omitted, we can't fix it. Therefore, I've also shortened the time range construct in the test to reduce the possibility of test failures. Fix #188
> fix: if start time is later than end, treat it as crossing midnight

- README-EN.md
- README.md
- maa-cli/src/config/task/condition.rs
- maa-cli/src/config/task/mod.rs
- maa-cli/src/main.rs
This condition is useful for tasks that are active every N days. For example, a infrastructure plan that has 6 plan in 2 days.
> feat: add condition `DayMod` for multi-day plan

- .github/workflows/ci.yml
- README-EN.md
- README.md
- maa-cli/schemas/asst.schema.json
- maa-cli/src/config/asst.rs
- maa-cli/src/main.rs
- maa-cli/src/run/mod.rs
- maa-cli/src/run/playcover.rs
The preset define some default value of connection configuration, only support `MuMuPro` and `PlayCover` now.
The old `type` have become alias `preset` for compatibility.
> feat: add `preset` field for connection configuration

- .github/actions/setup/action.yml
- .github/workflows/ci.yml
I have no idea but it seems that cache for coverage break the cache for build.
> ci: split coverage and test, install core with prebuilt maa

- README-EN.md
- README.md
- maa-cli/src/main.rs
There are three log prefix mod:
- Auto (default): print prefix when log to file, not otherwise;
- Always: always print prefix;
- Never: never print prefix.
> feat: add env `MAA_LOG_PREFIX` to control prefix in log

- Cargo.lock
- maa-cli/Cargo.toml
More details:
```
Updating aho-corasick v1.1.2 -> v1.1.3
Updating autocfg v1.1.0 -> v1.2.0
Updating backtrace v0.3.69 -> v0.3.71
Updating bitflags v2.4.2 -> v2.5.0
Updating bytes v1.5.0 -> v1.6.0
Updating clap v4.5.2 -> v4.5.4
Updating clap_derive v4.5.0 -> v4.5.4
Updating fastrand v2.0.1 -> v2.0.2
Updating git2 v0.18.2 -> v0.18.3
Updating h2 v0.3.24 -> v0.4.3
Updating heck v0.4.1 -> v0.5.0
Updating http v0.2.12 -> v1.1.0
Updating http-body v0.4.6 -> v1.0.0
Adding http-body-util v0.1.1
Removing httpdate v1.0.3
Updating hyper v0.14.28 -> v1.2.0
Updating hyper-tls v0.5.0 -> v0.6.0
Adding hyper-util v0.1.3
Updating indexmap v2.2.5 -> v2.2.6
Updating libz-sys v1.1.15 -> v1.1.16
Adding pin-project v1.1.5
Adding pin-project-internal v1.1.5
Updating regex v1.10.3 -> v1.10.4
Updating reqwest …
```
> chore(deps): update reqwest to `0.12` and no breaking updates for other crates

- .github/workflows/release.yml
- cliff.toml
- Re-add version and tag environment variables used by cliff;
- Don't generate links to GitHub profiles when running in CI.
> ci: fix changelog generation

- Cargo.lock
```
Updating `tuna` index
Updating base64 v0.21.7 -> v0.22.0
Updating bumpalo v3.15.4 -> v3.16.0
Updating cc v1.0.90 -> v1.0.92
Updating chrono v0.4.35 -> v0.4.37
Updating getrandom v0.2.12 -> v0.2.14
Updating itoa v1.0.10 -> v1.0.11
Updating libredox v0.0.1 -> v0.1.3
Updating memchr v2.7.1 -> v2.7.2
Updating openssl-sys v0.9.101 -> v0.9.102
Updating pin-project-lite v0.2.13 -> v0.2.14
Updating redox_users v0.4.4 -> v0.4.5
Updating regex-syntax v0.8.2 -> v0.8.3
Updating reqwest v0.12.2 -> v0.12.3
Updating rustls-pemfile v1.0.4 -> v2.1.2
Adding rustls-pki-types v1.4.1
Updating rustversion v1.0.14 -> v1.0.15
Updating security-framework v2.9.2 -> v2.10.0
Updating security-framework-sys v2.9.1 -> v2.10.0
Updating strsim v0.11.0 -> v0.11.1
Updating syn v2.0.55 -> v2.0.58
Updating tokio v1.36.0 …
```
> chore(deps): bump Cargo.lock

- .github/workflows/release.yml
- cliff.toml
Currently, the generated release notes include all changes starting from the latest stable tag. However, in this PR, non-stable releases (beta and nightly) will only include changes starting from the latest beta tag, making it easier to compare two beta releases.
> ci: match beta tag when release a non-stable release

- Cargo.lock
- maa-cli/Cargo.toml
- maa-cli/src/log.rs
- maa-cli/src/main.rs
The MSRV of clap_verbosity_flag is so high (1.73), and it's easy to implement a simple log flag by myself.
> refactor: remove clap_verbosity_flag

- maa-cli/src/log.rs
The `log_path` should return the log file path without ensuring the log directory exists. It should avoid touching files.
> fix: ensure log directory exists before creating log file

- .github/workflows/ci.yml
The macOS 12 runner is much slower than the macOS 14 runner, so we remove the macOS 12 runner from coverage jobs, and replace it with the macOS 14 runner in the build-feature jobs.
> ci: replace macOS 12 with macOS 14 in some CI jobs

- maa-cli/src/run/callback/mod.rs
Log the resolution and UUID messages as debug messages.
> feat: handle ResolutionGot and UuidGot messages

- maa-cli/src/command.rs
- maa-cli/src/config/mod.rs
- maa-cli/src/main.rs
This commit adds a new command `import` to easily import configuration files to the user's config directory with some validation.
> feat: new command `import` to import configuration files

- maa-cli/docs/en-US/config.md
- maa-cli/docs/zh-CN/config.md
- maa-cli/src/config/asst.rs
- maa-cli/src/run/mod.rs
If the `address` is absent, the cli will try to find the device automatically by `adb devices`, if there are multiple online devices, the first one will be used. If cli can not find any device, it will try to use the default address `emulator-5554`.
> feat: detect device address by `adb devices`

- maa-cli/docs/en-US/config.md
- maa-cli/docs/zh-CN/config.md
- maa-cli/src/config/task/mod.rs
- maa-cli/src/run/preset/copilot.rs
- maa-cli/src/run/preset/roguelike.rs
- maa-cli/src/value/mod.rs
- Rename `OptionalInput` to `Optional`;
- Rename `deps` to `conditions` in `Optional`;
- Rename `input` to `value` in `Optional` and can be any boxed `MAAValue`;
- Fix initialize order of values in an object:
The current sort implementation is incorrect. The `sort_by` function is only suitable for sorting elements with a total order, whereas the dependencies exhibit a partial order. In the current implementation, we define a total order that combines dependencies and key names, which is not transitive, even in the absence of circular dependencies. For instance, if A depends on B, B depends on C, and C depends on D, then it should be A < B < C < D. However, C and A are both `Optional` and do not directly depend on each other. Consequently, they will be compared by their keys, and the order …
> feat: improve optional value

- maa-cli/src/config/mod.rs
Files with same name but different extension will be treated as same config file, while only one file with same name is allowed.
This commit ensures that files with same name but different extension are removed after copying the new file.
> fix: ensure config file are unique after importing

- .github/workflows/release.yml
The unversioned archive is useful for a link that always points to the latest stable release, which used in our documentation.
> ci: create a unversioned archive for each platform

- maa-sys/Cargo.toml
- maa-sys/src/asst_type.rs
- maa-sys/src/error.rs
- maa-sys/src/task_type.rs
- Implement parse for `TouchMode`;
- Implement `const fn to_str` for `TouchMode` and `TaskType`;
- `AsRef<str>` for them is deprecated and will be removed at next minor version;
- Implement `COUNT`, `NAMES`, `VARIANCES` for them, which are generated at runtime automatically;
- All deserialize of them are implemented manually without derive macro.
> refactor(sys): parse and convert of `TouchMode` and `TaskType`

- Cargo.lock
- maa-cli/Cargo.toml
- maa-cli/src/installer/extract.rs
- Update git2 to 0.19
- Update zip to 2
- Bump Cargo.lock
> chore(deps): update compatible versions of git2 and zip

- maa-cli/src/config/task/mod.rs
Use `Official` as the default value for `client_type` in relevant tasks, even if `client_type` is not explicitly set.
> feat: use `Official` as the default value for `client_type`

- maa-cli/src/activity.rs
- maa-cli/src/cleanup.rs
- maa-cli/src/dirs.rs
- maa-cli/src/run/mod.rs
- maa-sys/src/lib.rs
These tests are ignored. If run test with `--ignored`, they will be executed. To run these tests, installation of MaaCore and resource is needed, and some environment variables are needed to be set. If in some cases, these requirements are not met, use `SKIP_CORE_TEST` to skip.
> test!: run tests even some environment variables are not set

- Cargo.lock
- maa-cli/Cargo.toml
Migrated from native-tls to rustls, resolving TLS issues on Windows; OpenSSL is no longer needed when the git2 feature is disabled.
> refactor!: switch from `native-tls` to `rustls`

- Cargo.lock
- Cargo.toml
- maa-cli/Cargo.toml
- maa-cli/src/main.rs
- maa-cli/src/run/mod.rs
- maa-dirs/Cargo.toml
- maa-dirs/src/lib.rs
The `dirs::*` functions depend on some environment variables, and this feature has been well tested. However, when running cargo tests in parallel, environment variables are shared by all threads, making the output of `dirs` functions unreliable. Therefore, we can split these tests to avoid them running alongside others.
> refactor: split `dirs` module into a separate crate

- .github/workflows/ci.yml
- .github/workflows/release.yml
The `ubuntu-latest` runner is currently based on Ubuntu 24.04, which has higher version of `glibc` than some users' systems.
Fixes: #358
> fix: use ubuntu-22.04 instead of ubuntu-latest for build jobs

- Cargo.lock
- crates/maa-cli/src/installer/maa_cli.rs
- crates/maa-dirs/Cargo.toml
- crates/maa-dirs/src/lib.rs
Change environment variables is not thread-safe, use a mock struct to avoid conflict. Because rust support ZST, so in normal case, there should be no overhead.
> test: use mock environment variables in maa-dirs tests

- .github/workflows/ci.yml
- crates/maa-cli/src/config/cli/mod.rs
- crates/maa-cli/src/config/cli/resource.rs
- Run tests for all packages in main test job;
- Make sure run test with no default features in no default build job;
- Minimize installation of nightly version rustfmt.
> ci: improve test jobs

- .github/workflows/ci.yml
To minimize CI usage when tests or linters fail.
> ci: run cross build and optional build after main build

- crates/maa-cli/config_examples/cli.toml
- crates/maa-cli/docs/en-US/config.md
- crates/maa-cli/docs/ja-JP/config.md
- crates/maa-cli/docs/ko-KR/config.md
- crates/maa-cli/docs/zh-CN/config.md
- crates/maa-cli/docs/zh-TW/config.md
- crates/maa-cli/schemas/cli.schema.json
- crates/maa-cli/src/config/cli/mod.rs
- crates/maa-cli/src/config/cli/resource.rs
- crates/maa-cli/src/installer/resource.rs
When the `warn_on_update_failure` option is enabled, maa will warn the user when the hot update fails instead of panicking.
Closes #371
> feat: add `warn_on_update_failure` option for hot update

- Cargo.lock
- Cargo.toml
With `native-tls`, we should get smaller binary size, better performance and safety.
> feat: switch reqwest to use native-tls

- crates/maa-cli/src/config/init.rs
I noticed that the corresponding field in `schemas/asst.schema.json` is `txwy`, not `Txwy`.
And when using `Txwy`, it results in a "Global resource Txwy not found" warnning. But in fact, we do have a resource at `.local/share/maa/resource/global/txwy/resource`. 
Therefore, I believe using `txwy` instead of `Txwy` during initialization is the correct approach.
> fix: use `txwy` instead of `Txwy` when init
