- Cargo.lock
> chore: bump lock

- config_examples/asst.toml
- maa-run/src/config/asst.rs
- maa-run/src/main.rs
- maa-sys/src/lib.rs
This is useful for adding other server game resources and platform specific resource.
> feat: add a field `resources` to specify additional resource files

- maa-cli/src/run/mod.rs
考虑到灵活性，我还是决定用根据 `cilent_type` 来了。
Close #32
> feat: load resources based on `cilent_type` and if use `PlayTools`

- .github/workflows/ci.yml
- maa-cli/src/installer/download.rs
- maa-cli/src/installer/maa_cli.rs
- maa-cli/src/installer/maa_core.rs
- maa-cli/src/main.rs
- Don't return error if connect failed during test;
- If the test time is set to 0, skip test;
- Add github release link to test links;
- Improve some output of version and download info.
> feat: import download

- Cargo.lock
- maa-cli/Cargo.toml
- maa-cli/share/fish/vendor_completions.d/maa.fish
- maa-cli/src/config/cli.rs
- maa-cli/src/main.rs
- Use `maa complete <shell>` to genarate completion script of given shell.
- Fish completion script.
> feat: add completion

- README-EN.md
- README.md
Only option "Maatouch" can be detected by maa-cli
> Change "MaaTouch" to "MAATouch" in documents

- config_examples/asst.toml
- maa-cli/src/config/asst.rs
- maa-cli/src/run/mod.rs
MaaAssistantArknights/MaaAssistantArknights#6872
@Cryolitia 帮忙看看？
> feat: add support for static options

- .github/workflows/ci.yml
- maa-cli/src/config/asst.rs
CC: @Cryolitia，这样跑测试应该就不会失败了吧。
> test: ignore tests that attempt to create a directory in user space

- .github/workflows/publish-aur.yml
- .github/workflows/release.yml
CC: @horror-proton，上传的 action 更新对 AUR 会有影响吗？
> ci: bump `actions/upload-artifact` and `actions/download-artifact` to `v4`

- README-EN.md
- README.md
- maa-cli/schemas/task.schema.json
- maa-cli/src/activity.rs
- maa-cli/src/config/task/client_type.rs
- maa-cli/src/config/task/condition.rs
- maa-cli/src/config/task/mod.rs
- maa-cli/src/main.rs
Command `maa activity` to show tips:
```
Opening side story stages:
- SSReopen-FC: 代理1~8
- FC-5: 糖组
- FC-6: 异铁组
- FC-7: 半自然溶剂
```
New condition `OnSideStory` which is true, if any side story stage is opening.
Close #139
> feat: read stage activity from StageActivity.json

- maa-cli/Cargo.toml
- maa-cli/src/run/mod.rs
- maa-cli/src/run/playcover.rs
Based on MaaAssistantArknights/MaaMacGui#14
> refactor: detect game ready and close game by TCP connection

- maa-cli/src/run/callback/mod.rs
- maa-cli/src/run/mod.rs
> feat: exit with error when taskchain error

- Cargo.lock
- maa-cli/Cargo.toml
- maa-cli/src/run/mod.rs
- maa-sys/Cargo.toml
- maa-sys/src/link.rs
And bump `maa-sys` to `0.3.0`.
> feat!: return the error when loading SharedLibrary fails

- README-EN.md
- README.md
- maa-cli/config_examples/tasks/daily.json
- maa-cli/config_examples/tasks/daily.toml
- maa-cli/config_examples/tasks/daily.yml
- maa-cli/schemas/task.schema.json
- maa-cli/src/config/task/client_type.rs
- maa-cli/src/config/task/condition.rs
- maa-cli/src/config/task/mod.rs
> feat: add `client` field to Weekday condition to adjust date

- maa-cli/src/config/asst.rs
> fix: default connection config for linux

- .github/actions/install-core/action.yml
- .github/actions/setup/action.yml
- .github/workflows/ci.yml
- .github/workflows/publish-homebrew.yml
- .github/workflows/release.yml
- use the latest stable release of cli;
- split setup action into two actions;
- quote all action expression with single quote to avoid wrong highlight and lint;
> ci: refactor workflows 

- README-EN.md
- README.md
Upstream PR: https://github.com/NixOS/nixpkgs/pull/254916
> docs(installation): add Nix/Linux

- maa-cli/src/installer/resource.rs
> feat: check git and ssh key availability before hot update

- maa-cli/src/dirs.rs
> test: remove MAA_*_DIR env vars before test

- maa-cli/src/config/task/client_type.rs
- maa-cli/src/config/task/mod.rs
- maa-cli/src/run/mod.rs
- maa-cli/src/run/preset/mod.rs
- maa-cli/src/value/mod.rs
See MaaAssistantArknights/MaaAssistantArknights#9658
> feat: set `client_type` for `Fight` and `Closedown` automatically

- maa-cli/src/run/preset/reclamation.rs
- maa-sys/src/task_type.rs
> fix: task name of reclamation algorithm

- maa-cli/src/run/preset/copilot.rs
Occasionally, tests may fail due to internet problems.
> test: retry 3 times for test that downloads files from internet

- crates/maa-cli/src/run/preset/roguelike.rs
https://github.com/MaaAssistantArknights/MaaAssistantArknights/pull/11521
> feat: add support for starting with seed in Sarkaz theme and mode 1

- Cargo.lock
- Cargo.toml
- crates/maa-sys/Cargo.toml
- crates/maa-sys/src/lib.rs
- Fix typo of screen cap method;
- Rename old get_image method and make it unsafe;
- New `get_image` method that return owned data;
- Make `get_uuid` method return a String.
> feat!(sys): improve methods to get image and device id

- Cargo.lock
- crates/maa-cli/Cargo.toml
- crates/maa-cli/src/run/mod.rs
- crates/maa-sys/Cargo.toml
- crates/maa-sys/src/lib.rs
- crates/maa-sys/src/link.rs
BREAKING CHANGE: the `get_null_size` is removed, use constant `NULL_SIZE` instead.
> feat(sys)!: add `load` related methods for Assistant safe API

- crates/maa-cli/docs/zh-CN/install.md
windows依赖库安装命令来自
[MaaAssistantArknights](https://github.com/MaaAssistantArknights/MaaAssistantArknights/tree/dev)
/DependencySetup_依赖库安装.bat
> docs: 在 install.md 中添加 windows 依赖库安装指引

- Cargo.lock
- crates/maa-cli/Cargo.toml
- crates/maa-cli/docs/zh-CN/config.md
- crates/maa-cli/src/config/asst.rs
- crates/maa-cli/src/run/external/mod.rs
- crates/maa-cli/src/run/external/playcover.rs
- crates/maa-cli/src/run/external/waydroid.rs
- crates/maa-cli/src/run/mod.rs
> Feat: 为Waydroid实现ExternalApp

- crates/maa-cli/src/run/callback/mod.rs
- crates/maa-cli/src/run/callback/summary.rs
- crates/maa-cli/src/run/preset/fight.rs
Need Test after new beta release.
> feat: adapt recent update of fight series

- DEVELOPMENT.md
Added detailed contribution process, code standards, and PR rules. Removed project structure section as it might be outdated soon.
> docs: update DEVELOPMENT.md with contribution guidelines

- crates/maa-cli/completions/maa.fish
Update `maa.fish` completions.
> Update completion for `maa roguelike JieGarden`
